### ISSUE TITLE
Error always logged on sync complete

### ISSUE THREAD

**Issue by bzbetty** [jsgoupil/quickbooks-sync#17]
We get a an error logged each sync with the message

[QBError] Out - {KEY} Sync Completed

trying to find out if there actually an error occuring that we need to fix, or if this should be an informational message instead of an error.

**Comment by jsgoupil** [comment]
@bzbetty Sorry but this seems to be your code logic? Is this coming from your LogMessage ?

**Comment by bzbetty** [comment]
I'm looking at line 406 of the Sync Manager

https://github.com/jsgoupil/quickbooks-sync/blob/1f795169ee32d7e453422dc689eb0edd13852da4/src/WebConnector/SyncManager.cs#L406

**Comment by jsgoupil** [comment]
I'm not sure what the problem is? LogMessage does not mean an error happened. LogMessage is called for anything going in or out the API.

**Comment by bzbetty** [comment]
The LogMessage is called with LogMessageType.Error, just means every completion is coming up in my logs as an error and not an info/debug message.

LogMessage(authenticatedTicket, LogMessageType.Error, LogDirection.Out, ticket, result);

**Comment by jsgoupil** [comment]
Ah you are right. I misread that... sorry! It should definitely not be logged as an error. Thanks for pointing this out!

**Comment by jsgoupil** [comment]
I think this would fix it:

```
try
{
    LogMessage(authenticatedTicket, LogMessageType.Close, LogDirection.In, ticket);

    var logMessageType = LogMessageType.Error;
    var result = "Invalid Ticket";

    if (authenticatedTicket != null)
    {
        result = "Sync Completed";
        logMessageType = LogMessageType.Close;
    }

    LogMessage(authenticatedTicket, logMessageType, LogDirection.Out, ticket, result);

    return result;
}
```

**Comment by bzbetty** [comment]
yeah that looks much better. thanks.
