### ISSUE TITLE
Question About Querying Items

### ISSUE THREAD

**Issue by valmont** [jsgoupil/quickbooks-sync#22]
I am looking to query items. I am interested in ItemNonInventoryRet, ItemInventoryRet, ItemInventoryAssemblyRet & ItemServiceRet.

Is there a way to only include these item types and not the other types? 

Here is my current query:
```
var request = new QbXmlRequest();
            var innerRequest = new ItemQueryRqType {
                MaxReturned = MaxReturned,
                iterator = IteratorType.Start,
                FromModifiedDate = SyncLog.FromDate,
                ToModifiedDate = SyncLog.ToDate,
                ActiveStatus = ActiveStatus.ActiveOnly
            };
```

**Comment by jsgoupil** [comment]
Hello. I believe it would be better if you ask that question on Stackoverflow. But from my expertise, I would say you should query each of these items with a different request for each of them.

https://developer-static.intuit.com/qbSDK-current/Common/newOSR/index.html

 * ItemNonInventoryQuery
 * ItemInventoryQuery
 * ItemInventoryAssemblyQuery
 * ItemServiceQuery
