### ISSUE TITLE
Help for integrating with my local database

### ISSUE THREAD

**Issue by Bhawan-Bhangu** [jsgoupil/quickbooks-sync#23]
Hi. I want to integrate this application for quickbook sync but not able how to use this example. Like I,m creating one console app and trying to use these methods but its not working. If you can help me that would be great. Like any other example using this quickbook_sync. Thanks in advance.

**Comment by jsgoupil** [comment]
Sorry, the documentation can be a little old, but this project is open source and you are welcome to push updates if something is incorrect.
I offer paid consultation if you need further help.

**Comment by Bhawan-Bhangu** [comment]
Thanks jsgoupil for quick respond. Yes I need to integrate and trying. I'll let you know for consultation. Thank you so much.
