### ISSUE TITLE
InvoiceAdd.InvoiceLineAdd items being reordered

### ISSUE THREAD

**Issue by daniel-geiselhart** [jsgoupil/quickbooks-sync#36]
Some items are getting reordered by InvoiceAdd.InvoiceLineAdd. Unable to see why this is happening

![image](https://user-images.githubusercontent.com/11393104/57632863-1ae87000-7568-11e9-8ca2-72e024294013.png)

![image](https://user-images.githubusercontent.com/11393104/57632830-0efcae00-7568-11e9-9559-9eb91a93d9cd.png)

<QBXML>
    <QBXMLMsgsRq onError="continueOnError">
        <InvoiceAddRq>
            <InvoiceAdd>
                <CustomerRef>
                    <ListID>80000007-1554843372</ListID>
                    <FullName>QB Desktop Test</FullName>
                </CustomerRef>
                <ARAccountRef>
                    <ListID>8000001E-1555443730</ListID>
                    <FullName>A/R</FullName>
                </ARAccountRef>
                <TxnDate>2019-05-10</TxnDate>
                <RefNumber>0008</RefNumber>
                <Memo>Owner Invoice ID 0008: momo 1</Memo>
                <ExternalGUID>{a66c95ac-fac9-43fa-822e-3219204a45c3}</ExternalGUID>
                <InvoiceLineAdd>
                    <ItemRef>
                        <ListID>800000F4-1555593041</ListID>
                        <FullName>01-0050 · Plans and Specs</FullName>
                    </ItemRef>
                    <Desc />
                    <Quantity>0.03</Quantity>
                    <Amount>3.00</Amount>
                    <SalesTaxCodeRef>
                        <ListID>80000002-1553892706</ListID>
                    </SalesTaxCodeRef>
                </InvoiceLineAdd>
                <InvoiceLineAdd>
                    <ItemRef>
                        <ListID>800000D2-1555593040</ListID>
                        <FullName>06-1000 · Rough Carpentry</FullName>
                    </ItemRef>
                    <Desc />
                    <Quantity>0.03</Quantity>
                    <Amount>3.69</Amount>
                    <SalesTaxCodeRef>
                        <ListID>80000002-1553892706</ListID>
                    </SalesTaxCodeRef>
                </InvoiceLineAdd>

**Comment by david-dawa** [comment]
I am also encountering this issue.

**Comment by rogerfar** [comment]
This has become an issue for us too, especially pushing large invoices with 100's of lines it is critical the order remains the same.

It looks like it is because of the code in `ObjectItems.cs` where it does the ordering on line 106, this is not a safe order, it will cause the order to be randomly jumbled.

I altered the code a bit so it keeps the correct order with a PR.

**Comment by jsgoupil** [comment]
After double checking the fix, the reason this was happening was because the sorting mechanism was unstable. Using `OrderBy` makes the sort stable.

Thanks for the fix.

**Comment by jsgoupil** [comment]
Fixed with e4f237f5417ceb21a7fc3c4bbad937b46f8dc2bd
Released as 2.0.1
