### ISSUE TITLE
How can i Iterator for JournalEntryAddRqType.

### ISSUE THREAD

**Issue by JoshiBhavik145** [jsgoupil/quickbooks-sync#42]
As i have to push Multi pal days entry of Night audit to QB JournalEntry.

I have scenario like i have to pass ascending order by dates Journal entry to QB, if i get error to pass any date entry, i need to stop from it, and need to solve. then again start from the error date.

**Comment by jsgoupil** [comment]
Oups, I am not understanding here. Thank you for trying your best :)
It seems more a question than a bug? Do you have code to share? Do you have an exception?

**Comment by JoshiBhavik145** [comment]
@jsgoupil  thanks for quick reply, I have solved my problem by using GroupStepQueryRequestBase and response. their is no bug , i just want to implement Iterator for JournalEntryAddRqType can we  inherit IQbIteratorRequest for JournalEntryAddRqType  too.

**Comment by jsgoupil** [comment]
I'm glad you figured it out! Good luck with your project.
