### ISSUE TITLE
.NET naming conventions

### ISSUE THREAD

**Issue by mscappini** [jsgoupil/quickbooks-sync#5]
Some simple changes that I have noticed so far that I would change to follow the .NET conventions. Feel free to disregard and close the issue if you disagree. :smile:

Interfaces like `QbRequest`, `QbIteratorRequest`, `QbResponse`, and `QbIteratorResponse` should begin with a capital `I`. (Were these autogenerated?)

This is a matter of opinion: I feel that `StepQueryResponseBase<T, Y>.GetName()` should be an abstract property if its only purpose is to return a string with a name. I think making it a property will convey the idea that it should be simple and nothing complicated.

**Comment by jsgoupil** [comment]
I agree on both.

I have been working in TypeScript before and I dropped usage of I for a long time. My other projects use I for all my interfaces :+1:
