### ISSUE TITLE
decimal precision in QUANTYPE

### ISSUE THREAD

**Issue by Davidcc** [jsgoupil/quickbooks-sync#56]
Hello, we are trying to send quantities such as 0.16667 as the quantity on a CreditMemoLineAdd, and the QBXML being generated is 0.17.

I believe this is due to the use of  
`return _value.ToString("F", CultureInfo.InvariantCulture);`

in the FLOATTYPE superclass. Since (I believe) QBXML supports 5 decimal places, would "F5" be more appropriate here?

**Comment by jsgoupil** [comment]
Sounds right. You could send a PR with unit tests, I'll be happy to merge. 
FYI, AmtType can only have 2 decimals

**Comment by Davidcc** [comment]
I have finished the changes but I think I need someone with more permissions to create a branch?

**Comment by jsgoupil** [comment]
You should create a fork, commit to your fork, then in github it will ask you to do a pull request.

**Comment by Davidcc** [comment]
Thanks for your help!

**Comment by jsgoupil** [comment]
No problem, I'll publish this today

**Comment by jsgoupil** [comment]
This is released as 3.0.2
I have released the WebConnector as well with the new version since we changed a public API (private->protected)
