### ISSUE TITLE
StepQueryWithIterator could pass ticket to interested methods

### ISSUE THREAD

**Issue by mscappini** [jsgoupil/quickbooks-sync#6]
I think the `StepQueryWithIterator` class could pass the `authenticatedTicket` to the `SaveMessage` and `RetrieveMessage` methods in lieu of the current `ticket` and `step`. This would be useful because (in my implementation, for example) the ticket I use inherits from the `AuthenticatedTicket` class and is tracked in memory while storing a state (associated with the ticket) that can be used throughout the step process. So passing the instance of the ticket would save one the trouble of looking up the authenticated ticket by the ticket ID in certain implementations.

**Comment by jsgoupil** [comment]
Yes it would be probably a better design.

**Comment by mscappini** [comment]
Big log here because I keep overwriting the commit to get the right commit message to close the related issue. Never done that before, super cool!
