### ISSUE TITLE
XmlCodeExporter Missing

### ISSUE THREAD

**Issue by jmawebtech** [jsgoupil/quickbooks-sync#69]
Hi,

I am using .NET Core 6 and I upgraded from .NET Standard 2.0.

I am in this file: 

\quickbooks-sync\src\XsdGenerator\Program.cs

I built the solution. I get a build error here:

Line 51

            var codeExporter = new XmlCodeExporter(codeNamespace, compileUnit, CodeGenerationOptions.GenerateProperties | CodeGenerationOptions.GenerateOrder);

It appears this code is unavailable in .NET Core. Is there a workaround?

**Comment by jsgoupil** [comment]
There is no plan to move this project from .NET 4.7.1 to .NET Core.
This XSD Generator is only used to prepare an object file.
Do you have any reason to move this project to a higher library?
