### ISSUE TITLE
Upgrade from old version

### ISSUE THREAD

**Issue by DanPatten** [jsgoupil/quickbooks-sync#74]
Hello I am upgrading an old project from version 0.0.3 to latest and it appears several of the references/class names have changed. Do you have a migration/changelog that can help with the migration? Thanks

**Comment by jsgoupil** [comment]
Sorry, this is not a big project enough to have kept a changelog from there.
You may ask questions here or hire me.

**Comment by DanPatten** [comment]
It turns out someone forked your library and added some extra types/logic so I am good now. Thanks!
